rg2_gripper:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_joint
  gains:
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_gripper:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_joint
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1